### ISSUE TITLE
Decimals notation

### ISSUE THREAD

**Issue by Ghiaccio1o** [IridiumIO/PolyCut#4]
Hello!
Program is brillant but i have this issue: the gcode generated contain decimals numbers whit a comma "X,Y"...I understand this is the correct notation, but my Neptune 4 doesnt recognize instructions unless noted whit a dot "X.Y"
Is there any way to at least locally fix this?

**Comment by Iridium-IO** [comment]
Good catch, it's actually generating according to whatever your computer is set to - mine uses a dot, so I forgot to account for the fact that others may not.

Before I go digging for this, can I confirm that your PC would normally separate decimals with a comma instead of a period?

That is, other programs would show "10,24" instead of "10.24"

**Comment by Ghiaccio1o** [comment]
Thanks fot the quick answer.
Well, i dont know if my pc have a particular setting in this regard, after all when i use the keyboard I type how i want...especially since some programs requires to input commas, others ask me to put periods. 
As language my pc is setted on italian language whit american keyboard.  And i have the exact same issue using similar inkscape's plugins.
Anyway i must add that my slicers like Cura output the file whit periods, so they work fine...

**Comment by Iridium-IO** [comment]
Ah yep, it's because the default system culture for Italian (it-IT) uses commas as a decimal separator. 

Do you mind testing if this build fixes the issue?

[PolyCut.zip](https://github.com/IridiumIO/PolyCut/files/14414549/PolyCut.zip)

**Comment by Ghiaccio1o** [comment]
I would, but unfortunately both chrome and windows defender are blocking that archive.
https://www.microsoft.com/en-us/wdsi/threats/malware-encyclopedia-description?name=Trojan%3AScript%2FWacatac.B!ml&threatid=2147735503

**Comment by Iridium-IO** [comment]
It's a false positive, probably because it's an exe inside a zip file (GitHub doesn't allow putting exe files directly in comments so you have to zip it first) 


The only thing I've changed is switching how the GCode is generated. Instead of calling `Decimal.ToString`, it now calls Decimal.ToString(System.Globalization.Culture.InvariantCulture). Nothing else is different.

However if you don't feel safe running in then that's fair enough :)

**Comment by lucas14145** [comment]
Hello,
same problem here, my printer uses dots in gcode as well. I gave a try to your patch but the program crashes while generating gcode even when run as an admin... any idea?
I will manually modify some gcode file to give PolyCut a try, It seem very promissing and exactly what I was looking for!
Anyway thanks for all the work done so far, i'm looking forward for future updates.
lucas

**Comment by Iridium-IO** [comment]
> Hello, same problem here, my printer uses dots in gcode as well. I gave a try to your patch but the program crashes while generating gcode even when run as an admin... any idea? I will manually modify some gcode file to give PolyCut a try, It seem very promissing and exactly what I was looking for! Anyway thanks for all the work done so far, i'm looking forward for future updates. lucas

Can you please check the event viewer for the crash log and paste it here so I can figure out what's causing it?

1. Right click start > Event Viewer
2. In the left pane, click  Windows Logs > Application
3. Find the most recent polycut error (there might be two, one after the other; one with source `Application Error` and the other with source `.NET Runtime`

**Comment by lucas14145** [comment]
Nom de l’application défaillante PolyCut.exe, version : 1.0.0.0, horodatage : 0x65a80000
Nom du module défaillant : KERNELBASE.dll, version : 10.0.19041.3996, horodatage : 0xb756c9ff
Code d’exception : 0xe0434352
Décalage d’erreur : 0x000000000002cf19
ID du processus défaillant : 0x3094
Heure de début de l’application défaillante : 0x01da72cf4ea081c2
Chemin d’accès de l’application défaillante : C:\Users\lucas\Desktop\PolyCut.exe
Chemin d’accès du module défaillant: C:\Windows\System32\KERNELBASE.dll
ID de rapport : 274b428d-aab1-4873-ac9f-bbc304da3dca
Nom complet du package défaillant : 
ID de l’application relative au package défaillant : 


Application: PolyCut.exe
CoreCLR Version: 8.0.224.6711
.NET Version: 8.0.2
Description: The process was terminated due to an unhandled exception.
Exception Info: System.InvalidCastException: Conversion from string "96.509" to type 'Double' is not valid.
 ---> System.FormatException: The input string '96.509' was not in a correct format.
   at Microsoft.VisualBasic.CompilerServices.Conversions.ParseDouble(String Value, NumberFormatInfo NumberFormat)
   at Microsoft.VisualBasic.CompilerServices.Conversions.ToDouble(String Value, NumberFormatInfo NumberFormat)
   --- End of inner exception stack trace ---
   at Microsoft.VisualBasic.CompilerServices.Conversions.ToDouble(String Value, NumberFormatInfo NumberFormat)
   at PolyCut.Core.GCode.Parse(String line)
   at PolyCut.GCodeGeometry..ctor(String instr)
   at PolyCut.PreviewPage.compileGCodes(String gCode)
   at PolyCut.PreviewPage.DrawToolPaths()
   at PolyCut.PreviewPage..ctor(MainViewModel viewmodel)
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeDirectByRefWithFewArgs(Object obj, Span`1 copyOfArgs, BindingFlags invokeAttr)
   at System.Reflection.MethodBaseInvoker.InvokeWithOneArg(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.CreateServiceAccessor(ServiceIdentifier serviceIdentifier)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(ServiceIdentifier serviceIdentifier, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
   at Wpf.Ui.Controls.NavigationView.GetNavigationItemInstance(INavigationViewItem viewItem)
   at Wpf.Ui.Controls.NavigationView.NavigateInternal(INavigationViewItem viewItem, Object dataContext, Boolean addToNavigationStack, Boolean isBackwardsNavigated)
   at Wpf.Ui.Controls.NavigationView.Navigate(Type pageType, Object dataContext)
   at Wpf.Ui.NavigationService.Navigate(Type pageType)
   at PolyCut.MainViewModel.GenerateGcode()
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at PolyCut.Application.Main()


is that what you're looking for?

**Comment by Iridium-IO** [comment]
Yes that's it :) 

It seems the original fix _did_ work, but when it tries to read the GCode later, it gets confused because now it has a decimal point instead of a comma in the number. 

Can you try this version to see if it's fixed? 

[PolyCut_RegionalFixv2.zip](https://github.com/IridiumIO/PolyCut/files/14550103/PolyCut_RegionalFixv2.zip)

**Comment by lucas14145** [comment]
Yes, it works! thanks for that one.

**Comment by Iridium-IO** [comment]
Excellent, I've made it a proper release and will close this issue.
At some point I'll create an option to choose the format of the exported GCode as I'm sure someone will run into the opposite problem down the track
